version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
#    env_file:
#      - .env
    environment:
      - VITE_API_URL="https://taiga-labs.pro/matapi/api"
      - VITE_BOT_USERNAME=matrix_simple_bot