version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
#    env_file:
#      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_BOT_USERNAME=${VITE_BOT_USERNAME}